repos:
-   repo: https://github.com/python/black.git
    rev: stable
    hooks:
    -   id: black
        language_version: python3.7

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.701
    hooks:
    -   id: mypy
        language_version: python3.7
